const INPUT_NAME = 'INPUT_NAME';
const INCREMENT = 'INCREMENT';
const DECREMENT = 'DECREMENT';
const HTTP_POST = 'HTTP_POST';
const WS_RECEIVE = 'WS_RECEIVE';

export const MUTATION = {
  INPUT_NAME,
  INCREMENT,
  DECREMENT,
  HTTP_POST,
  WS_RECEIVE,
};
